include: package:very_good_analysis/analysis_options.3.0.2.yaml
linter:
  rules:
    public_member_api_docs: false
    lines_longer_than_80_chars: false
    comment_references: false
    avoid_print: false
analyzer:
  exclude:
    - lib/**.g.dart
