name: yookassa_client
description: Dart REST client for Yookassa Payments API
version: 1.0.0

repository: https://github.com/glin94/yookassa-dart-client
issue_tracker: https://github.com/glin94/yookassa-dart-client/issues
homepage: https://github.com/glin94/yookassa-dart-client

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  dio: ^4.0.6
  freezed_annotation: ^2.2.0
  json_annotation: ^4.7.0
  retrofit: ^3.3.1
  uuid: ^3.0.7

dev_dependencies:
  build_runner: ^2.3.2
  freezed: ^2.2.0
  json_serializable: ^6.5.3
  retrofit_generator: ^4.2.0
  test: ^1.22.1
  very_good_analysis: ^3.0.1
